# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97485121fd667176fa6f45035cd7bbc03b8551a2c1739780c9d814357abb4d44d2db06e4f574eb80aae78b3a4aa205f8f93ef772a195e5fecf6cf1e30c866fc2

test:
  secret_key_base: 9886b2637327cc54732c9945ced96a7f79e144e5bfa73d7df881c754224eb14c3bde5ccc3bfd1e1a6a3885719a736f1b63d5e6056595dab00db8e48b5624ef5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
